# Configuration for chatgptd
openai_api_key: "your-api-key-here"
model: "gpt-4"
temperature: 0.7
max_tokens: 1500

# Directive handling
directives:
  master_path: "../Utilsrepo/directives/AI_Directives.txt"
  fallback_path: "directives/AI_Directives.txt"
  auto_sync_check: true
